#!/usr/bin/env Rscript

# This script generates dendrograms from PhyloPhlAn outputs.

# load the optparse library
library(optparse)

# Create command line argument parser
help_description <- "

This script generates dendrograms from PhyloPhlAn output files.

The following positional arguments are required:

species.tree (Input file): This tree is generated by PhyloPhlAn
species.aln (Input file): This fasta file is generated by PhyloPhlAn
output_tree_1.png (Output file): This is the first dendrogram image written
output_tree_2.png (Output file): This is the second dendrogram image written"

args <- OptionParser(usage = "%prog species.tre species.aln output_tree_1.png output_tree_2.png", 
                      add_help_option = TRUE, prog='phylophlan_ggtree.R',
                      description=help_description )
args_list <- parse_args(args, positional_arguments=TRUE)

# load other libraries after optparse to not load them on help
library(ggplot2)
library(ggtree)
library(RColorBrewer)

# read newick tree
species.tre <- read.tree( args_list$args[1] )
# create ggtree object
species.gg <- ggtree( species.tre )
# read in metadata file
sample_list = data.frame(species.tre$tip.label)
names(sample_list) = "SampleID"
sample_list$annotation = ifelse(grepl("GCA_", sample_list$SampleID), "Reference", "MAG")

# add metadata to dendrogram plot
species.gg <- species.gg %<+% sample_list

col_tip = c("MAG" = "#483D8B", Reference = "#5F9EA0")
# plot with color terminal edges and sample names with Country and add tiplabels
png( args_list$args[3], width = 5, height = 6, res = 300, units = "in" )
# strainphlan_tree_1.pdf
species.gg +  
  geom_tippoint( size = 3, aes( color = annotation) ) +
  aes( branch.length = 'length' ) + scale_color_manual(values = col_tip) +
  theme_tree2() + theme(legend.position="right")
temp <- dev.off()
# visualize tree with multiple sequence alignment (MSA)

# path to alignment file
species.aln = (args_list$args[2])
# plot tree with slice of MSA
png( args_list$args[4], width = 7, height = 6, res = 300, units = "in" )
# strainphlan_tree_2.pdf
msaplot( species.gg + geom_tippoint( size = 3, aes( color = annotation) ), 
         species.aln, window = c( 1,200 ), 
         color = brewer.pal(6, "Set3") ) + scale_color_manual(values = col_tip) +
  theme( legend.position = 'right' )
temp <- dev.off()


