#!/bin/bash

BOX_NAME="bioBakery.box"
package_includes="WELCOME.pdf,bioBakeryWallpaper.png,bioBakeryWallpaper.pptx"

function assistance () { # show this help
    echo "build stuff"
    echo "Available arguments:"
    grep "function.*#" "$0" \
	| egrep -v 'grep|sed' \
	| sed -e 's|function \(.*\)[ \t]*(.*#\(.*\)$|\1 - \2|'
}

function gui () { # build the gui vagrantbox
    cd biobakery-gui && pwd
      vagrant up
    cd -
}

function package () { # package the gui vagrantbox
    cd biobakery-gui && pwd
      vagrant halt
      vagrant package \
          --include "${package_includes}" \
          --output $BOX_NAME
    cd -
}

function dist () { # zip the packaged box
    package
    mv -v biobakery-gui/$BOX_NAME biobakery_dist/
    zip -r bioBakery_`date '+%F'`.zip biobakery_dist/
}

function clean() { # clean up 
    ls *.zip $BOX_NAME | xargs -I%s bash -c "test -f %s && rm -vf %s"

    cd biobakery-gui && pwd
      vagrant destroy -f
      file=disk.vdi; test -f $file && rm -vf $file
    cd -
}

function all() { # build the gui vagrantbox, then package, and zip it
    gui
    dist
}

for arg in "$@"; do
    echo "${arg}" | grep -q '\-h' && assistance && exit
    eval "${arg}"
done
