FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y python python-dev python-pip apt-transport-https openjdk-8-jre wget zip
RUN pip install boto3 cloudpickle awscli

RUN pip install anadama2

# install kneaddata and dependencies
RUN pip install kneaddata==0.7.3 --no-binary :all:

RUN wget http://tandem.bu.edu/trf/downloads/trf409.linux64 && \
    mv trf409.linux64 /usr/local/bin/trf && \
    chmod +x /usr/local/bin/trf

# install fastqc
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip && \
    unzip fastqc_v0.11.9.zip && \
    chmod 755 FastQC/fastqc && \
    mv FastQC /usr/local/bin/ && \
    ln -s /usr/local/bin/FastQC/fastqc /usr/local/bin/fastqc && \
    rm fastqc_v0.11.9.zip 

WORKDIR /tmp

