FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y python python-dev python-pip apt-transport-https openjdk-8-jre wget
RUN pip install boto3 cloudpickle awscli

RUN pip install anadama2

# install kneaddata and dependencies
RUN pip install kneaddata --no-binary :all:

RUN wget http://tandem.bu.edu/trf/downloads/trf409.linux64 && \
    mv trf409.linux64 /usr/local/bin/trf && \
    chmod +x /usr/local/bin/trf

WORKDIR /tmp

