####
# Main make driver script
####

# Dependencies
# Get mercurial
# Get Scons
# Install python
# Install R
# Make sure the R version matches the RPy2 version
# Make sure to build a sfle directory structure as you go
# Glob the modules directory install programs

DIR_Modules = modules
Modules := $(wildcard $(DIR_Modules)/*.bread)
# Will eventually use an include statement to incude all the bread make files.
all: biobakery

.PHONY: all install clean

biobakery: 

install: 

clean: 
