name: Issue template
description: Provide feedback on this tool
title: "[Include a brief but informative description of the issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the bioBakery! Please note that we use a Discourse forum (https://forums.biobakery.org) for interaction with our user community, including fielding bug reports and feature requests, rather than GitHub. You are welcome to open an issue here, but please note that it will be automatically closed, and while we will review it, it is not likely to receive a response. If you are looking for a response, please make your post to an appropriate Discourse topic instead.
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement of closure
      options:
        - label: I understand that only issues opened at https://forums.biobakery.org will receive responses.
          required: true
  - type: textarea
    id: feedback
    attributes:
      label: What would you like to say?
      placeholder: Provide additional details about your issue here
