FROM biobakery/base
RUN apt-get install -y python-pip
RUN apt-get install -y breadcrumbs
RUN apt-get install -y ccrepe
RUN apt-get install -y graphlan
RUN apt-get install -y humann
RUN apt-get install -y metaphlan
RUN apt-get install -y picrust-cmd
RUN apt-get install -y qiimetomaaslin
RUN apt-get install -y maaslin
RUN apt-get install -y graphlan
RUN apt-get install -y lefse
RUN apt-get install -y micropita


