# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "Biobakery-gui"
  config.vm.box_url = "http://huttenhower.sph.harvard.edu/biobakery-shop/vagrant/gui/biobakery.box"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", 1024]
    #vb.customize ["modifyvm", :id, "--vram", 64]
    #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

  end

end
