# -*- mode: ruby -*-

Vagrant.configure("2") do |config|


  config.vm.box = "Biobakery-gui"
  config.vm.box_url = "./biobakery.box"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    if ! ENV.include? "VAGRANT_VB_MEMORY" || ENV["VAGRANT_VB_MEMORY"].to_i <= 0
      mem = 1024
    else
      mem = ENV["VAGRANT_VB_MEMORY"].to_i
    end

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", mem]
    #vb.customize ["modifyvm", :id, "--vram", 64]
    #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

  end

end
