# -*- mode: ruby -*-
# vi: set ft=ruby :

VIRTUALBOX_RAM_AVAILABLE = 2048

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.box_check_update = false

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = false
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", VIRTUALBOX_RAM_AVAILABLE]
  end
  config.vm.provision :shell, :path => "provision.sh"
end
