FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y python python-dev python-pip apt-transport-https openjdk-8-jre wget
RUN pip install boto3 cloudpickle awscli

RUN pip install anadama2

# install kneaddata and dependencies
RUN pip install biobakery_workflows

WORKDIR /tmp

