# -*- mode: ruby -*-

VIRTUALBOX_RAM_AVAILABLE = 8192

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    # set the username and password
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.ssh.insert_key=false

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", VIRTUALBOX_RAM_AVAILABLE]

    file_to_disk = File.realpath( "." ).to_s + "/disk.vdi"

    if ARGV[0] == "up" && ! File.exist?(file_to_disk)
      #puts "Creating 5GB disk #{file_to_disk}."
      vb.customize [ 'createhd', 
                     '--filename', file_to_disk, 
                     '--format', 'VDI', 
                     '--size', 5000 * 1024 ] # 5 GB 
      vb.customize [ 'storageattach', :id, 
                     '--storagectl', 'SATAController', 
                     '--port', 1, '--device', 0, 
                     '--type', 'hdd', '--medium', 
                     file_to_disk ]
    end

  end

  # Provision via shell script
  config.vm.provision :shell, :path => "../provision-biobakery-core.sh", privileged: false
  config.vm.provision :shell, :path => "./provision-biobakery-nogui.sh"
end
